import Navbar from "@/components/common/navigation/navbar";
import "./globals.css";
import Footer from "@/components/common/footer";




export const metadata = {
  title: "HCL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full flex flex-col font-statosh">
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
